org: andersonkaiti
service: foodiary-api

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  runtime: nodejs22.x
  architecture: arm64
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    JWT_SECRET: ${env:JWT_SECRET}
    BUCKET_NAME: !Ref UploadsBucket
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:PutObject
          # Resource: !GetAtt UploadsBucket.Arn
          Resource: !Sub '${UploadsBucket.Arn}/*'

package:
  individually: true

build:
  esbuild:
    minify: true
    sourcemap: false

functions:
  signin:
    handler: src/functions/signin.handler
    events:
      - httpApi:
          path: /signin
          method: POST

  signup:
    handler: src/functions/signup.handler
    events:
      - httpApi:
          path: /signup
          method: POST

  me:
    handler: src/functions/me.handler
    events:
      - httpApi:
          path: /me
          method: GET

  create-meal:
    handler: src/functions/create-meal.handler
    events:
      - httpApi:
          path: /create-meal
          method: POST

  meals:
    handler: src/functions/list-meals.handler
    events:
      - httpApi:
          path: /meals
          method: GET

  get-meal-by-id:
    handler: src/functions/get-meal-by-id.handler
    events:
      - httpApi:
          path: /meals/{mealId}
          method: GET

resources:
  Resources:
    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: foodiary-uploads-andersonkaiti